name: Container Publish
on:
  push:
    branches:
      - master

permissions:
  packages: write

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@v9

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container
        run: nix build -L .#container

      - name: Upload container to ghcr.io
        run: |
          docker load < result
          docker tag "fueledbyjordan/jordanmurray_xyz:$(git rev-parse --short HEAD)" "ghcr.io/fueledbyjordan/jordanmurray_xyz:$(git rev-parse --short HEAD)"
          docker push "ghcr.io/fueledbyjordan/jordanmurray_xyz:$(git rev-parse --short HEAD)"
